### ISSUE TITLE
Delete with children - exception

### ISSUE THREAD

**Issue by manjirinamjoshi** [radekg/node-zookeeper-explorer#18]
Delete with children is causing 
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)

The recursive callback function "_$deregisterFromZooKeeper" is causing this issue.

Any proposal for fixing it ?

Thanks,
Manjiri

**Comment by radekg** [comment]
H Manjiri, I'll happily accept a pull request.
